### ISSUE TITLE
Bootstrap containers nesting

### ISSUE THREAD

**Issue by mabhub** [makinacorpus/php-layout#1]
I think in Bootstrap 3, containers (`.container` or `.container-fluid`) should not be nested (with a few exception for global layout, outside of a grid).

http://getbootstrap.com/css/#grid-nesting

So for your example in README, markup should be :

```html
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
        
      <div class="row">
        <div class="col-md-6">
          <item id="A1" />
          <item id="A4" />
        </div>
        <div class="col-md-6">
          
          <div class="row">
            <div class="col-md-6">
              <item id="A2" />
              <item id="A5" />
            </div>
            <div class="col-md-6">
              <item id="A3" />
            </div>
          </div>
          
        </div>
      </div>
        
      <item id="A6" />
      <item id="A7" />
    </div>
  </div>
</div>
```

**Comment by pounard** [comment]
Thank you very much for the tip, indeed, I should fix this. Not solely the sample, but the Bootstrap rendered code needs to be fixed to.

I was not awaiting for someone to take a look at this so quickly; thanks for the issue!

**Comment by pounard** [comment]
Thanks!
